### ISSUE TITLE
make en failed

### ISSUE THREAD

**Issue by gan** [google/blockly-games#79]
Hello, 

I pulled project and followed the build wiki.
`make deps`, `make en`
I got some errors, then the page is blank.
````
Bird - en - uncompressed:
third-party/build/closurebuilder.py: Scanning paths...
third-party/build/closurebuilder.py: 2441 sources scanned.
third-party/build/closurebuilder.py: Building dependency tree..
Traceback (most recent call last):
  File "third-party/build/closurebuilder.py", line 293, in <module>
    main()
  File "third-party/build/closurebuilder.py", line 229, in main
    tree = depstree.DepsTree(sources)
  File "/Users/xgan/Documents/Blockly/blockly-games/third-party/build/depstree.py", line 56, in __init__
    raise NamespaceNotFoundError(require, source)
depstree.NamespaceNotFoundError: Namespace "Blockly.Blocks.variables" never provided. Required in PathSource appengine/js/js-blocks.js

Bird - en - compressed:
appengine/bird/js/bird.js:527: WARNING - Redeclared variable: image
  var image = document.getElementById('nest');
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

appengine/third-party/SoundJS/soundjs-NEXT.js:310: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:311: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:312: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:314: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:315: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:316: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:317: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:2400: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:4023: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:6819: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:7046: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:7106: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:7441: WARNING - Bad type annotation. type not recognized due to syntax error. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs-NEXT.js:7459: WARNING - Bad type annotation. type not recognized due to syntax error. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:310: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:311: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:312: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:314: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:315: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:316: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:317: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:2400: WARNING - Bad type annotation. type annotation incompatible with other annotations. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:4023: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:6819: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:7046: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:7106: WARNING - Bad type annotation. expected closing } See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:7441: WARNING - Bad type annotation. type not recognized due to syntax error. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/SoundJS/soundjs.js:7459: WARNING - Bad type annotation. type not recognized due to syntax error. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

appengine/third-party/blockly/core/block.js:1149: WARNING - Redeclared variable: i
    for (var i = 0; i < extensionNames.length; ++i) {
             ^^^^^

appengine/third-party/blockly/generators/javascript.js:258: WARNING - Redeclared variable: comment
          var comment = Blockly.JavaScript.allNestedComments(childBlock);
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

appengine/third-party/midi-js/examples/inc/timer.js:187: WARNING - String continuations are not recommended. See https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations

appengine/third-party/midi-js/generator/nodejs/packageWAVs.js:87: WARNING - String continuations are not recommended. See https://google.github.io/styleguide/jsguide.html#features-strings-no-line-continuations

appengine/bird/js/blocks.js:29: ERROR - required "Blockly.Blocks.logic" namespace never provided
goog.require('Blockly.Blocks.logic');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

appengine/bird/js/blocks.js:30: ERROR - required "Blockly.Blocks.math" namespace never provided
goog.require('Blockly.Blocks.math');
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2 error(s), 33 warning(s)

````
Can you help me?

**Comment by NeilFraser** [comment]
Thanks for the report.  This is due to an upstream change in Blockly.  You can follow the progress here:
https://groups.google.com/forum/#!topic/blockly/7vlZwGofbd4

The offending change in Blockly is here:
https://github.com/google/blockly/pull/1796

Waiting to see what @AnmAtAnm says.

**Comment by AnmAtAnm** [comment]
I've reverted the PR that caused this issue. Will discuss the correct route forward in person or on the mailing list (since several other people will likely use such `goog.require()` statements.
